<?php
declare(strict_types=1);
require dirname(__DIR__) . '/uts/ortam.php';

$bugun = date('Y-m-d');
$ted = insert('suppliers', ['name' => 'Çerçeve Toptan', 'phone' => '0532 111 22 33', 'created_at' => uts_simdi(), 'updated_at' => uts_simdi()]);
$mus = insert('customers', ['first_name' => 'Ayşe', 'last_name' => 'Yılmaz', 'phone' => '05321234567', 'birth_year' => 1980]);
$cer = insert('frame_items', ['brand' => 'Ray-Ban', 'model' => 'RB5154', 'color' => 'Siyah', 'qty' => 1, 'supplier_id' => $ted, 'created_at' => uts_simdi(), 'updated_at' => uts_simdi()]);
$sip = insert('orders', ['first_name' => 'Ayşe', 'last_name' => 'Yılmaz', 'customer_id' => $mus, 'transaction_type' => 'gozluk', 'frame_item_id' => $cer,
    'lens_type' => 'Progresif 1.6', 'order_stage' => 'teslim_edildi', 'delivered_at' => '2026-03-15 14:00:00']);
$rx = insert('prescription_records', ['order_id' => $sip]);
insert('prescription_lens_items', ['prescription_id' => $rx, 'lens_no' => 1, 'eye' => 'R', 'lens_type' => 'Progresif 1.6', 'supplier_id' => $ted]);

echo "1) Doğrulamalar\n";
hata_bekle(fn() => garanti_ekle(['order_id' => $sip, 'kalem' => 'x', 'urun' => 'A']), 'kalem zorunlu', 'kalemini');
hata_bekle(fn() => garanti_ekle(['order_id' => $sip, 'kalem' => 'cerceve', 'urun' => '  ']), 'ürün zorunlu', 'Ürün');
hata_bekle(fn() => garanti_ekle(['order_id' => 999, 'kalem' => 'cerceve', 'urun' => 'A']), 'olmayan sipariş', 'bulunamadı');
hata_bekle(fn() => garanti_ekle(['kalem' => 'cerceve', 'urun' => 'A']), 'sipariş ya da müşteri gerekir', 'bağlı');
$iptal = insert('orders', ['customer_id' => $mus, 'order_stage' => 'iptal']);
hata_bekle(fn() => garanti_ekle(['order_id' => $iptal, 'kalem' => 'cerceve', 'urun' => 'A']), 'iptal siparişe garanti açılmaz', 'İptal');
hata_bekle(fn() => garanti_ekle(['customer_id' => $mus, 'kalem' => 'cerceve', 'urun' => 'A', 'baslangic' => '31.02.2026']), 'geçersiz tarih', 'Başlangıç');
hata_bekle(fn() => garanti_ekle(['customer_id' => $mus, 'kalem' => 'cerceve', 'urun' => 'A', 'baslangic' => '2026-05-01', 'bitis' => '2026-04-01']), 'bitiş başlangıçtan önce olamaz', 'Bitiş');
hata_bekle(fn() => garanti_ekle(['customer_id' => $mus, 'kalem' => 'cerceve', 'urun' => 'A', 'ay' => 200]), 'süre sınırı', '120');

echo "2) Siparişten garanti\n";
$oneri = garanti_siparis_onerileri($sip);
esit(['cerceve', 'cam'], array_column($oneri, 'kalem'), 'gözlükte çerçeve + cam önerilir');
esit('Ray-Ban RB5154 Siyah', $oneri[0]['urun'], 'çerçeve adı stoktan');
esit($ted, $oneri[0]['supplier_id'], 'çerçevenin tedarikçisi');
esit('Progresif 1.6', $oneri[1]['urun'], 'cam adı siparişten');
$ids = garanti_siparisten_olustur($sip);
esit(2, count($ids), 'iki garanti açıldı');
$g1 = row('SELECT * FROM garantiler WHERE id = ?', [$ids[0]]);
esit('2026-03-15', $g1['baslangic'], 'başlangıç = teslim tarihi');
esit('2028-03-15', $g1['bitis'], 'varsayılan 24 ay');
esit($mus, (int) $g1['customer_id'], 'müşteri siparişten');
ok(preg_match('/^[A-Za-z0-9]{22}$/', (string) $g1['token']) === 1, 'anahtar 22 karakter');
ok($g1['token'] !== row('SELECT token FROM garantiler WHERE id = ?', [$ids[1]])['token'], 'anahtarlar farklı');
esit([], garanti_siparis_onerileri($sip), 'açılan kalem tekrar önerilmez');
esit([], garanti_siparisten_olustur($sip), 'ikinci kez oluşturma boş döner');
$gunes = insert('orders', ['customer_id' => $mus, 'transaction_type' => 'gunes_gozlugu', 'frame_info' => 'Persol 0714', 'order_stage' => 'hazirlandi']);
esit([['kalem' => 'gunes', 'urun' => 'Persol 0714', 'supplier_id' => null]], garanti_siparis_onerileri($gunes), 'güneş gözlüğünde tek kalem');
$tamir = insert('orders', ['customer_id' => $mus, 'transaction_type' => 'tamir', 'order_stage' => 'teslim_edildi', 'created_at' => '2026-06-01 10:00:00']);
esit([], garanti_siparis_onerileri($tamir), 'tamir siparişine garanti önerilmez');
setting_set('garanti_gunes_ay', '12');
$gg = garanti_siparisten_olustur($gunes);
esit(date('Y-m-d', strtotime('+12 months')), row('SELECT bitis FROM garantiler WHERE id = ?', [$gg[0]])['bitis'], 'ayardaki süre (12 ay), başlangıç bugün');
$el = garanti_ekle(['order_id' => $sip, 'kalem' => 'diger', 'urun' => 'Kordon', 'baslangic' => '2026-01-01', 'bitis' => '2026-07-01', 'seri_no' => 'SN-77', 'supplier_id' => 9999]);
esit(null, row('SELECT supplier_id FROM garantiler WHERE id = ?', [$el])['supplier_id'], 'olmayan tedarikçi bağlanmaz');

echo "3) Durum ve kalan süre\n";
esit('gecerli', garanti_durumu($g1, '2026-10-01')['kod'], 'geçerli');
esit('green', garanti_durumu($g1, '2026-10-01')['ton'], 'uzun süre: yeşil');
esit('amber', garanti_durumu($g1, '2028-03-01')['ton'], 'son 30 gün: sarı');
esit(0, garanti_durumu($g1, '2028-03-15')['kalan_gun'], 'bitiş günü hâlâ geçerli');
esit('bitti', garanti_durumu($g1, '2028-03-16')['kod'], 'bitişten sonra doldu');
esit('iptal', garanti_durumu(['durum' => 'iptal', 'bitis' => '2030-01-01'])['kod'], 'iptal');
esit('12 gün', garanti_kalan_metni(12), 'kalan: gün');
esit('1 yıl 5 ay', garanti_kalan_metni(530), 'kalan: yıl + ay');
esit('Ayşe Y.', garanti_musteri_kisa('Ayşe', 'Yılmaz'), 'müşteriye kısa ad');

echo "4) Talepler (tamir geçmişi)\n";
$gid = $ids[0];
hata_bekle(fn() => garanti_talep_ekle($gid, ' '), 'şikâyet zorunlu', 'Şikâyet');
$t1 = garanti_talep_ekle($gid, 'Sol menteşe gevşedi');
hata_bekle(fn() => garanti_talep_ekle($gid, 'başka'), 'aynı anda tek açık talep', 'açık');
hata_bekle(fn() => garanti_durum_degistir($gid, 'iptal'), 'açık talepte iptal yok', 'Açık talebi');
esit(1, garanti_rozet(), 'rozet: açık talep');
garanti_talep_tedarikciye($t1);   // tedarikçi verilmezse garantinin tedarikçisi
$t = row('SELECT * FROM garanti_talepleri WHERE id = ?', [$t1]);
ok($t['durum'] === 'tedarikcide' && (int) $t['supplier_id'] === $ted && $t['gonderim'] === $bugun, 'tedarikçiye gönderildi');
hata_bekle(fn() => garanti_talep_tedarikciye($t1), 'ikinci gönderim yok', 'mağazadaki');
$metin = garanti_tedarikci_metni(garanti_bul($gid), $t);
ok(str_contains($metin, 'Sol menteşe') && str_contains($metin, 'Ray-Ban') && !str_contains($metin, '0532123'), 'tedarikçi metni: arıza ve ürün var, müşteri telefonu yok');
hata_bekle(fn() => garanti_talep_kapat($t1, 'tamamlandi'), 'sonuç türü zorunlu', 'Sonucu');
hata_bekle(fn() => garanti_talep_kapat($t1, 'reddedildi'), 'red sebebi zorunlu', 'sebebini');
q('UPDATE garanti_talepleri SET created_at = ? WHERE id = ?', [date('Y-m-d H:i:s', strtotime('-10 days')), $t1]);
$onceBitis = row('SELECT bitis FROM garantiler WHERE id = ?', [$gid])['bitis'];
garanti_talep_kapat($t1, 'tamamlandi', 'tamir', 'Menteşe değişti', 150.5);
$t = row('SELECT * FROM garanti_talepleri WHERE id = ?', [$t1]);
ok($t['durum'] === 'tamamlandi' && $t['sonuc_tur'] === 'tamir' && (float) $t['maliyet'] === 150.5 && $t['kapanis'] !== null, 'talep tamamlandı');
esit(date('Y-m-d', strtotime($onceBitis . ' +10 days')), row('SELECT bitis FROM garantiler WHERE id = ?', [$gid])['bitis'], 'tamirde geçen 10 gün garantiye eklendi');
hata_bekle(fn() => garanti_talep_kapat($t1, 'tamamlandi', 'tamir'), 'kapalı talep kapanmaz', 'kapalı');
garanti_talep_yeniden_ac($t1);
esit('tedarikcide', row('SELECT durum FROM garanti_talepleri WHERE id = ?', [$t1])['durum'], 'yeniden açılınca tedarikçide');
setting_set('garanti_sure_uzat', '0');
$b = row('SELECT bitis FROM garantiler WHERE id = ?', [$gid])['bitis'];
garanti_talep_kapat($t1, 'reddedildi', '', 'Düşürme hasarı, garanti dışı');
esit($b, row('SELECT bitis FROM garantiler WHERE id = ?', [$gid])['bitis'], 'reddedilen talep süreyi uzatmaz');
esit(0, garanti_rozet(), 'rozet sıfır');
$t2 = garanti_talep_ekle($gid, 'Vida düştü');
garanti_talep_kapat($t2, 'tamamlandi', 'tamir');
esit(2, count(garanti_talepleri($gid)), 'tamir geçmişi: iki talep');
garanti_talep_yeniden_ac($t1);
hata_bekle(fn() => garanti_talep_ekle($gid, 'x'), 'yeniden açılan varken yeni talep açılmaz', 'açık');
hata_bekle(fn() => garanti_talep_yeniden_ac($t2), 'açık varken ikincisi yeniden açılmaz', 'açık');
garanti_talep_kapat($t1, 'reddedildi', '', 'Düşürme hasarı');
esit([$tamir], array_map('intval', array_column(garanti_musteri_tamirleri($mus, '2026-03-15'), 'id')), 'müşterinin tamir siparişleri');
esit([], garanti_musteri_tamirleri($mus, '2026-07-01'), 'garantiden önceki tamir sayılmaz');

$eski = garanti_ekle(['customer_id' => $mus, 'kalem' => 'cerceve', 'urun' => 'Eski', 'baslangic' => '2020-01-01', 'ay' => 24]);
hata_bekle(fn() => garanti_talep_ekle($eski, 'kırık'), 'süresi dolana talep açılmaz', 'dolmuş');
garanti_durum_degistir($el, 'iptal');
hata_bekle(fn() => garanti_talep_ekle($el, 'kırık'), 'iptal garantiye talep açılmaz', 'İptal');
hata_bekle(fn() => garanti_durum_degistir($el, 'x'), 'geçersiz durum', 'Geçersiz');

echo "5) Düzenleme ve arama\n";
garanti_guncelle($gid, ['urun' => 'Ray-Ban RB5154 Siyah 49', 'seri_no' => 'RB-998877', 'bitis' => '2028-06-01', 'kapsam' => 'Menteşe dahil']);
$g = garanti_bul($gid);
ok($g['seri_no'] === 'RB-998877' && $g['bitis'] === '2028-06-01' && $g['tedarikci'] === 'Çerçeve Toptan', 'güncellendi, tedarikçi korundu');
hata_bekle(fn() => garanti_guncelle($gid, ['bitis' => '2020-01-01']), 'bitiş başlangıçtan önce olamaz', 'Bitiş');
$ara = static fn(string $q, string $f = 'tumu'): array => array_map('intval', array_column(garanti_ara($q, $f), 'id'));
ok(in_array($gid, $ara('ayşe'), true) || in_array($gid, $ara('Ayşe'), true), 'ada göre');
ok(in_array($gid, $ara('1234567'), true), 'telefona göre');
esit([$gid], $ara('RB-9988'), 'seri no');
esit([$gid], $ara(garanti_no($gid)), 'garanti no (G00001)');
ok(in_array($gid, $ara('#' . str_pad((string) $sip, 5, '0', STR_PAD_LEFT)), true), 'sipariş no');
ok(!in_array($eski, $ara('', 'aktif'), true) && !in_array($el, $ara('', 'aktif'), true), 'geçerli listesinde dolan ve iptal yok');
ok(in_array($eski, $ara('', 'tumu'), true), 'tümü');
$yakin = garanti_ekle(['customer_id' => $mus, 'kalem' => 'cam', 'urun' => 'Yakında biter', 'baslangic' => date('Y-m-d', strtotime('-23 months -10 days')), 'ay' => 24]);
esit([$yakin], $ara('', 'bitiyor'), '30 günde bitecekler');
$t3 = garanti_talep_ekle($yakin, 'Çizik');
esit([$yakin], $ara('', 'talep'), 'açık talepliler');
esit([], $ara('', 'tedarikcide'), 'tedarikçide olan yok');

echo "6) Karekod, barkod, silme\n";
ok(garanti_bul_token((string) $g['token'])['id'] == $gid, 'anahtarla bulunur');
esit(null, garanti_bul_token('kisa'), 'geçersiz anahtar');
esit(null, garanti_bul_token("x' OR '1'='1"), 'enjeksiyon denemesi');
$url = garanti_url($g);
ok(str_contains($url, 'garanti.php?m=7&k=' . $g['token']), 'karekod adresi mağaza + anahtar');
$b = barkod_coz($url);
ok($b['tur'] === 'garanti' && $b['hedef'] === 'garantiler.php?id=' . $gid, 'barkod: karekod → garanti kaydı');
$b = barkod_coz(garanti_no($gid));
ok($b['tur'] === 'garanti' && $b['hedef'] === 'garantiler.php?id=' . $gid, 'barkod: garanti no');
$b = barkod_coz('https://x.test/durum.php?m=3&k=YOKBOYLEANAHTAR12345');
ok($b['tur'] !== 'garanti', 'durum adresi garanti sanılmaz');
garanti_sil($yakin);
esit(0, (int) scalar('SELECT COUNT(*) FROM garanti_talepleri WHERE garanti_id = ?', [$yakin]), 'silinince talepleri de gider');
esit(null, garanti_bul($yakin), 'garanti silindi');

bitir();
